### ISSUE TITLE
代码在make test时会报错

### ISSUE THREAD

**Issue by xjcvip007** [lhmRyan/deep-supervised-hashing-DSH#1]
你好，你的代码在make test 时会报
make: **\* [.build_release/src/caffe/test/test_memory_data_layer.o] Error 1
的错误，但是我直接编译官网的caffe不会出现这个问题，请教一下是为什么呢？

**Comment by lhmRyan** [comment]
make test报错的原因：因为我对caffe的代码进行了一些修改，所有data layer的输出label都从单标签变成了多标签，所以代码里很多的datum->set_label都改成了datum->add_label，但是我没改test的代码，所以可能有点不匹配，因此会报错。我的建议是跳过make test，因为make all之后代码就可以用了，test的功能主要是测试代码实现的正向、反向传播是否正确，不编译的话也不影响使用。

**Comment by lhmRyan** [comment]
你好，

    make test的原因：因为我对caffe的代码进行了一些修改，data
layer的label从单标签变成了多标签，所以代码里很多的datum->set_label都改成了datum->add_label，但是我没改test的代码，所以可能有点不匹配，因此会报错。我的建议是跳过make
test，因为make all之后代码就可以用了，test的功能主要是测试代码实现的正向、反向传播是否正确，不编译的话也不影响使用。

祝好
刘昊淼

2016-10-26 21:41 GMT+08:00 xjcvip007 <notifications@github.com>:

**Comment by xjcvip007** [comment]
你好，特别感谢你的回复，在你的帮助下，代码已经能够运行，但允许我再问一个小问题，我如果要把DSH用在其他数据集上，Hashingloss中的参数bi_margin和tradeoff是否需要修改呢，还是说需要重新调参呢？期待你的回复～

**Comment by lhmRyan** [comment]
可能需要适当地调整一下这两个参数。可以先按照论文中的方法设置参数，然后在此基础上进行调整。个人感觉，tradeoff这个参数相对比较稳定，可以先固定住，只调整bi_margin。

**Comment by xjcvip007** [comment]
好的，非常感谢你的回复～

**Comment by xjcvip007** [comment]
你好，很抱歉再次打扰你，最后请教一个小问题，你在计算map的compute_map.m文件中，为什么query_label和database_label为什么都是用同一个数据集的label呢，这应该是需要我们自己修改的吧～期待您的回复～

**Comment by lhmRyan** [comment]
这个只是一个例子，如果需要的话，可以按照你自己的测试协议修改。

**Comment by xjcvip007** [comment]
非常感谢～
