### ISSUE TITLE
Must use GPU?

### ISSUE THREAD

**Issue by helen0461** [lhmRyan/deep-supervised-hashing-DSH#10]
I try to make this project on the VMware with Ubuntu without GPU and failed.
error info. is follow:
In file included from ./include/caffe/common.hpp:19:0,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layers/hashing_loss_layer.hpp:6,
                 from src/caffe/layers/hashing_loss_layer.cpp:4:
./include/caffe/util/device_alternate.hpp:15:36: error: no ‘void caffe::HashingLossLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class ‘caffe::HashingLossLayer<Dtype>’
     const vector<Blob<Dtype>*>& top) { NO_GPU; } \
                                    ^
src/caffe/layers/hashing_loss_layer.cpp:118:1: note: in expansion of macro ‘STUB_GPU’
 STUB_GPU(HashingLossLayer);
 ^
./include/caffe/util/device_alternate.hpp:19:39: error: no ‘void caffe::HashingLossLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class ‘caffe::HashingLossLayer<Dtype>’
     const vector<Blob<Dtype>*>& bottom) { NO_GPU; } \
                                       ^
src/caffe/layers/hashing_loss_layer.cpp:118:1: note: in expansion of macro ‘STUB_GPU’
 STUB_GPU(HashingLossLayer);
 ^
Makefile:572: recipe for target '.build_release/src/caffe/layers/hashing_loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/hashing_loss_layer.o] Error 1
make: *** 正在等待未完成的任务....

I think that without GPU cause this problem. Can I make this without GPU or should I change a device?
Looking forward to receive reply! THX!

**Comment by lhmRyan** [comment]
Hi, you could compile without GPU by turning on the CPU_ONLY switch in Makefile.config

**Comment by helen0461** [comment]
Thank you for your reply.
I had compile caffe without GPU by turning on the CPU_ONLY switch in Makefile.config successfully.
However, I compile this project with the same Makefile.config unsuccessfully.

**Comment by helen0461** [comment]
I also had try to edit the solver_mode in solver.prototxt file and still doesn't work.

**Comment by lhmRyan** [comment]
You can try to comment line 117~119 in "src/caffe/layers/hashing_loss_layer.cpp" (#ifdef CPU_ONLY STUB_GPU(HashingLossLayer); #endif). It worked on my computer.
