### ISSUE TITLE
关于hashing_image_data_layer.cpp的问题

### ISSUE THREAD

**Issue by xjcvip007** [lhmRyan/deep-supervised-hashing-DSH#11]
你好，仔细阅读过你hashing_image_data_layer.cpp的代码，有个疑问，比如batch_size设200，cat_per_iters设为10，则每个类中取20个样本，之后如何构造相似/不相似样本对呢？因为你的代码中同一个类的20个样本，是顺序保存在cpu_data中的，之后读取的话是不是相似的样本对会明显多于非相似的？谢谢~

**Comment by lhmRyan** [comment]
你好，构造样本对的过程是在“hashing_loss_layer.cpp”里实现的，构造的时候遍历batch中的所有样本对（共n*(n-1)/2 个）。其中的相似样本对数是远小于非相似样本对的

**Comment by xjcvip007** [comment]
好的，感谢你的回复
