### ISSUE TITLE
测试的时候是一张图片为输入，还是两张？

### ISSUE THREAD

**Issue by liquor7** [lhmRyan/deep-supervised-hashing-DSH#12]
作者您好，
       您在文章中计算loss的时候是和Siamese网络一样三个输入，您也解释了在线生成图片对的好处以及使用单层网可以达到和Siamese网相近的cost。
       我想请问一下，您测试的时候是单张输入还是两张？

**Comment by lhmRyan** [comment]
测试的时候输入单张图像，具体可以看提取二值码的代码“extract_code.sh”

**Comment by liquor7** [comment]
谢谢~~~~
可是最近我用imagenet数据集做测试，mAP实在太低了，只有9%。每个类我取了20张图片，每个图片做了17种变换，将这样的17种变换作为一个类，最终我就有20000个类，每个类18张图片。可是我取训练集和测试集的时候，是以原imagenet前700个类中图片包括所做的变换作为训练集，后300个类中图片包括变换作为训练集的，也就是训练集和测试集是不满足类的同分布，但是满足变换的同分布。
我没有用HashImageData层，今天正在尝试，但是出了bug（*** Aborted at 1513590014 (unix time) try "date -d @1513590014" if you are using GNU date ***)  我正在看您的层定义源码，可能是因为标签的格式不同。
但是只用普通的data层，mAP为什么这么低....好忧伤....
from  一名在自动化大厦忧伤的孩子

**Comment by liquor7** [comment]
我刚刚好像忘记艾特了...脱线了....cry) :           @lhmRyan

**Comment by lhmRyan** [comment]
类别数多的时候，如果使用普通的data layer，很有可能一个batch内没有相似样本而只有不相似样本，所以模型的训练肯定是有问题的。而且类别数这么多的时候，训练metric learning或者hashing的模型需要很多的trick，我也正在尝试中。

**Comment by liquor7** [comment]
@lhmRyan  谢谢！ 即候  文祺
