### ISSUE TITLE
HashLoss Layer question

### ISSUE THREAD

**Issue by aiaini66** [lhmRyan/deep-supervised-hashing-DSH#13]
dear:
   I'm recreating your program of DSH, but I found that the hash loss layer does not have reverse-propagating code. Did you not published  it ? Is it convenient  for you to provide it? thank you a lot!

**Comment by lhmRyan** [comment]
Hi, the back-propagation code is intergrated into the forward propagation code. It's in the "void HashingLossLayer<Dtype>::Forward_cpu" function, where "bout" corresponds to the gradient.

**Comment by aiaini66** [comment]
oh, I got it ,thank you very much !

**Comment by lhmRyan** [comment]
You're welcome
