### ISSUE TITLE
mAP become worse when I change the dimension of the hash code to 24 or larger. 

### ISSUE THREAD

**Issue by suanrong** [lhmRyan/deep-supervised-hashing-DSH#14]
The default hash code dim is 12. I change it to 24 directly in train_test.prototxt instead of  fine_tuning. Other hyperparameters remain unchanged. and I run train_full.sh and get a worse mAP of 0.6853 while mAP of 12 dim is 0.6987.  I don‘’t know why . When I change it to 36. I get a mAP of 0.5839.

Could you give me some advise to improve the result when the hash dim is larger? Thx~

**Comment by lhmRyan** [comment]
hi, you need to change "bi_margin" when changing code dim. According to our paper, you should set bi_margin=2*code dim. This should give you correct results.

**Comment by suanrong** [comment]
Thank you! [捂脸，我把margin忘了]
