### ISSUE TITLE
Error generating at 64%

### ISSUE THREAD

**Issue by Lischip** [lhmRyan/deep-supervised-hashing-DSH#2]
Good day!

I cannot seem to generate the algorithm as is. The following error occurs at 64% (Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/hashing_loss_layer.cpp.o)

[...]/include/caffe/util/device_alternate.hpp:15:36: error: no ‘void caffe::HashingLossLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class ‘caffe::HashingLossLayer<Dtype>’
     const vector<Blob<Dtype>*>& top) { NO_GPU; } \
                                    ^
[...]/src/caffe/layers/hashing_loss_layer.cpp:118:1: note: in expansion of macro ‘STUB_GPU’
 STUB_GPU(HashingLossLayer);
 ^
[...]/include/caffe/util/device_alternate.hpp:19:39: error: no ‘void caffe::HashingLossLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class ‘caffe::HashingLossLayer<Dtype>’
     const vector<Blob<Dtype>*>& bottom) { NO_GPU; } \
                                       ^
[...]/src/caffe/layers/hashing_loss_layer.cpp:118:1: note: in expansion of macro ‘STUB_GPU’
 STUB_GPU(HashingLossLayer);
 ^
src/caffe/CMakeFiles/caffe.dir/build.make:2054: recipe for target 'src/caffe/CMakeFiles/caffe.dir/layers/hashing_loss_layer.cpp.o' failed
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/hashing_loss_layer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lhmRyan** [comment]
I suggest you compiling the code using the "make all" command, that should work.

**Comment by Lischip** [comment]
Thank you for replying so fast! I used 'make -j4' at the previous attempts to compile it, but when using 'make all' it results in the same error. I am able to compile the original caffe with both the 'make -j4' and 'make all' commands.

The steps I take on my ubuntu 16.04 LTS system are renaming the Makefile.config.example to Makefile.config and editing it to fit my system. Then I create a build folder and use 'cmake ..' and 'make all' within the build folder.

When the 'cmake ..' command is in progress it only throws the error it cannot detect CUDA, and continues building without it.

Thanks for your time and patience!

**Comment by lhmRyan** [comment]
@Lischip  Hi, I've tested my code on an ubuntu 16.04 server, it works just fine for me. Here's how I compiled the code:

Step 1: git clone the code
Step 2: cd to the directory
Step 3: rename Makefile.config.example to Makefile.config, and add the path of libhdf5 as:

INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial

Step 4: uncomment "USE_CUDNN", note that this version of the code does not support cudnn v5, so I used cudnn v4, and added the path to "Makefile.config" accordingly.
Step 5: make all -j8

I didn't use cmake, so I think that cmake might be the cause of your problem. You could try to compile the code by simply using "make all".

Another solution could be to implement the forward_gpu and backward_gpu functions for the hashing_loss_layer. But the above solution could be easier.
