### ISSUE TITLE
请问'hashing_image_data_layer'有什么用？

### ISSUE THREAD

**Issue by ToTheBeginning** [lhmRyan/deep-supervised-hashing-DSH#3]
readme上说为了在线生成图像对，可是hashing_loss_layer不是已经实现了这个功能了吗？而且protext里也没有用这个data layer，您能解释下吗？

**Comment by lhmRyan** [comment]
hashing_image_data_layer的作用是进行class-aware sampling，即每次随机选择一定数目的类别（cat_per_iter），然后再从每类选择一定数目的样本（batch_size/cat_per_iter）。这个layer主要是针对类别数很多的数据集。例如，对于ImageNet来说，一共有1000个类别，如果采取随机采样的策略，那么有可能一个batch内的图像对绝大多数（甚至全部）都是dissimilar，不利于网络的训练。

**Comment by ToTheBeginning** [comment]
Thanks。CIFAR-10用不用这个layer应该差别不太大吧，因为只有10个类。

**Comment by lhmRyan** [comment]
是的。所以在例程中CIFAR-10数据集上用的是普通的data layer。

**Comment by suanrong** [comment]
nuswide的例程也没用这个layer诶，为什么啊，nuswide不是有21类吗，感觉挺多的啊

**Comment by lhmRyan** [comment]
@suanrong 这个layer的作用主要是为了保证在每个batch中都存在一定数量的相似样本对和不相似样本对。对于单标签数据库来说，如果类别数量比较大或者类别比较不均衡的时候，有可能随机采样的时候，一个batch中没有相似样本对（每个类的样本只有一个），或者有些类别的相似样本对数量很少，被采样到的概率很低。对于多标签数据库来说，这个问题并不严重，所以就没用这个layer。

所以简单来说，当数据库为单标签数据库，且类别数量很多或者每类的样本数量不均衡的时候，需要使用这个layer，其他情况下可以不用。

**Comment by suanrong** [comment]
@lhmRyan 谢谢~
