### ISSUE TITLE
请问map的计算是只在测试集中查询吗？

### ISSUE THREAD

**Issue by ToTheBeginning** [lhmRyan/deep-supervised-hashing-DSH#4]
我看有的人用的是测试集图片查训练集图片。请问哪一个更标准一些？

**Comment by lhmRyan** [comment]
是的。两种做法都有人在用，你说的那种做法用的人稍微多一点。但是我们在文章中也解释了为什么要用现在这种测试协议，主要是因为这种协议的难度更大，更符合“数据库不断增长，但是模型仍然是原来训练的模型”这种情况。

**Comment by ToTheBeginning** [comment]
好的，谢谢！
