### ISSUE TITLE
Nothing in the distribute file after the make all -j4 ,compared to the original caffe,there is no profile,why?

### ISSUE THREAD

**Issue by renhui19931001** [lhmRyan/deep-supervised-hashing-DSH#5]

**Comment by lhmRyan** [comment]
I'm not sure if I understood your question correctly. For distribution version of caffe, you need to run make distribute. After that, some files would be copied to the "distribute" directory.

The source code in this repository is mostly the same with the original caffe, except for a few changes:
(1) The codes were modified to support multi-label LMDB/LevelDB;
(2) Some new layers are added.
For the rest parts, the codes are exactly the same as the original caffe.
